import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import { Navbar } from "./components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

const sfPro = localFont({
  src: "../../public/SF-Pro-Display-Medium.otf",
  variable: "--font-sf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${sfPro.variable}`}>
        <div className="fixed h-screen w-full bg-gradient-to-br from-indigo-50 via-white to-cyan-100" />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
