name: backend deploy

on:
  push:
    branches:
    - main
    paths:
      - 'packages/back-end/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install Dependencies
        run: cd packages/back-end && npm install

      - name: Build
        run: cd packages/back-end && npm run build

      - name: Set up Heroku
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku git:remote -a short-links-backend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        run: |
          git subtree push --prefix packages/back-end heroku main
